# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wStOOix_lzE6lBLhtumuwM4J_1j8Yqx
"""

from matplotlib import colors
import pandas as pn
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()
student = pn.read_csv('student_scores.csv')
# print(student)
student = student.rename(columns={"Name": "Naam", "Age": "Sex"})
# print(student)
student.columns= student.columns.str.lower().str.strip()
student= student.drop_duplicates().fillna(0)
# print(student)
# student.to_csv("Clean file.csv", index=False)
# from google.colab import files
# files.download("Clean file.csv")
print(student[['math_score', 'science_score', 'english_score']].mean())
counts = student['gender'].value_counts()
print(counts)
avg_index = ('math_score', 'science_score', 'english_score')
avg_variables = (76.1, 74.3, 75.2)
plt.bar(avg_index , avg_variables, color= "pink", width=(0.2))
plt.title ('Average score per subject')
plt.xlabel ('Subject')
plt.ylabel ('Average score')
plt.ylim(70.00,80.00)
plt.legend()
plt.grid(True)
plt.show()
plt.pie(counts, labels=counts.index, autopct='%2.2f%%')
plt.title('Gender distribution')
plt.show()